import re

fields = ["last name",
          "first name",
          "mi",
          "address",
          "city",
          "state",
          "zip",
          "social security number",
          "home telephone number",
          "b. information about how to set-up or change your direct deposit",
          "set-up direct deposit",
          "change direct deposit account",
          "bank/financial institution information",
          "name",
          "city",
          "state",
          "zip",
          "choose type of account - note: we are only able to deposit benefit payments into one account.",
          "please verify the transit routing number with your bank.",
          "a routing number beginning with the number 5 is not valid",
          "bank transit/routing number",
          "personal account number",
          "c. direct deposit cancellation request",
          "please complete this section if you are canceling your direct deposit agreement",
          "cancel my direct deposit agreement",
          "effective date",
          "d. signature of individual",
          "signature of individual",
          "date",
          "a. attending physician's statement (please print)",
          "name of patient",
          "home telephone number",
          "date of birth",
          "social security number",
          "employer name/address",
          "employer telephone number",
          "normal pregnancy",
          "a) expected delivery date",
          "b) actual delivery date",
          "c) delivery type",
          "date first unable to work",
          "date hospitalized",
          "all other conditions",
          "patient information",
          "a) height",
          "weight",
          "b) date of first visit regarding current condition?",
          "c) date patient caused work beacuse of condition?",
          "d) did you advise patient to cease work?",
          "if yes, when?",
          "e) has the patient been treated for the same/similar condition in the past?",
          "if yes, when?",
          "if yes, please describe",
          "f) is the patient's condition due to injury or sickness involving the patient's employment?",
          "diagnosis and treatment",
          "primary diagnosis",
          "a) what is the primary diagnosis preventing your patient from working?",
          "please include primary icd and/or dsm iv multi-axial diagnoses and codes",
          "b) date of last examination",
          "c) describe reported symptoms",
          "d) describe physical findings (mris, x-rays, emg/ncv studies, lab test, clinical findings, gaf etc.)",
          "other conditions (please attach additional information as necessary)",
          "are there other conditions that prevent your patient from working? if so, please list with information as follows:",
          "a) secondary icds",
          "diagnosis",
          "secondary icds",
          "diagnosis",
          "b) describe reported symptoms",
          "c) describe physical findings (mris, x-rays, emg/ncv studies, lab test, clinical findings, gaf etc.)",
          "treatment",
          "a) describe the patient's current treatment program (include facilities name/address if applicable)",
          "b) medications (please list all medications including dosage and frequency)",
          "c) has patient been hospitalized?",
          "date hospitalized",
          "through",
          "d) was surgery performed? cpt 4 code(s)",
          "date surgery performed",
          "name/address of facility",
          "e) is the patient still under your care?",
          "final date of treatment",
          "claimant name",
          "social security number",
          "other providers: please supply complete name, contact information and specialty of any other treating physicians or hospital.",
          "name, specialty, address, phone #, fax #, treatment from, to",
          "physical capabilities",
          "a) patient's ability to: (please check number of hours per workday and how often)",
          "b) patient's ability to: (please check)",
          "c) patients ability to lift/carry (please check)",
          "d) patient's ability to perform (please check)",
          "a) when do you expect improvement in the patient's capabilities?",
          "b) restrictions (activities patient should not do)",
          "c) limitations (activities patient cannot do)",
          "print or type name",
          "degree",
          "medical specialty",
          "street address",
          "telephone number",
          "city",
          "state",
          "zip code",
          "fax",
          "signature of physician",
          "date",
          "ssn or employer's number",
          "are you, the physician, related to this patient?",
          "if yes, what is the relationship?",
          "attending physician statement (please print)",
          "part i: to be completed by patient",
          "name of patient (last name, suffix, first name, mi)",
          "social security number",
          "date of birth (mm/dd/yy)",
          "home telephone number",
          "employer telephone number",
          "employer name",
          "part ii: to be completed by physician or treating provider",
          "a. complete this section for pregnancy, then go to section c",
          "expected delivery date (mm/dd/yy)",
          "actual delivery date (mm/dd/yy)",
          "delivery type",
          "date of first visit for this pregnancy (mm/dd/yy)",
          "date hospitalized (mm/dd/yy)",
          "diagnosis:",
          "icd code:",
          "did you advise your patient to stop working?",
          "if yes, on what date (mm/dd/yy)",
          "were there any complications causing your patient to stop working prior to her expected delivery date?",
          "if yes, please explain",
          "b. complete this section for all conditions except pregnancy, then go to section c",
          "date of first visit for this current condition(s) (mm/dd/yy)",
          "date of last office visit (mm/dd/yy)",
          "date of next office visit (mm/dd/yy)",
          "did you advise your patient to stop working?",
          "if yes, on what date (mm/dd/yy)?",
          "has the patient been treated for the same/similar condition in the past?",
          "if yes, please provide treatment dates (mm/dd/yy)",
          "from",
          "through",
          "is the patient's condition work related?",
          "patient's height",
          "patient's weight",
          "primary diagnosis",
          "primary icd code",
          "secondary diagnosis",
          "secondary icd code",
          "has the patient been hospitalizes?",
          "if yes, date hospitalized (mm/dd/yy)",
          "through (mm/dd/yy)",
          "was surgery performed?",
          "if yes, what procedure was performed?",
          "cpt code",
          "date surgery performed (mm/dd/yy)",
          "what is your treatment plan? please include all medications.",
          "attending physician statement (continued)",
          "patient name (last name, first name, mi, suffix)",
          "date of birth (mm/dd/yy)",
          "other providers: are you aware of or have you referred your patient to other treating providers? if yes, please provide complete name, contact information and specialty of any other treating physicians.",
          "name, specialty, address, phone #",
          "have you advise the patient to return to work?",
          "expected return to work date (mm/dd/yy)",
          "part-time hours per day",
          "c. fuctional capacity",
          "(activities patient cannot do), please initial here",
          "restrictions and/or limitations",
          "if your patient has current restrictions (activities patient should not do) and/or limitation (activities patient cannot do) list below. please be specific and understand that a reply of \"no work\" or \"totally disabled\" will not enable us to evaluate your patient's claim for benefits and may result in us having to contact you for clarification.",
          "please provide the duration of these restrictions and limitations. from (mm/dd/yy)",
          "to (mm/dd/yy)",
          "d. signature of attending physician",
          "the above statements are true and complete to the best of my knowledge and belief.",
          "physician name (last name, first name, mi, suffix) please print",
          "degree/specialty",
          "address",
          "city",
          "state",
          "zip",
          "telephone number",
          "fax number",
          "physician tax id number",
          "are you related to this patient?",
          "if yes, what is the relation?",
          "signature of physician",
          "date",
          "insured's signature",
          "date signed",
          "printed name",
          "social security number",
          "i signed on behalf of the insured as",
          "my spouse:",
          "(name)",
          "(telephone number)",
          "other family member",
          "(name / relationship)",
          "(telephone number)",
          "other person:",
          "(name / relationship)",
          "(telephone number)",
          "claimant signature",
          "date",
          "printed name",
          "social security number",
          "i signed on behalf of the claimant as",
          "insured's signature",
          "date signed",
          "printed name",
          "social security number",
          "i signed on behalf of the insured as",
          "attending physician statement (continued)",
          "patient name (last name, first name, mi, suffix)",
          "date of birth (mm/dd/yy)",
          "have you advised the patient to work?",
          "expected return to work date (mm/dd/yy)",
          "full time",
          "part time",
          "part-time hours per day",
          "c. functional capacity",
          "(activities patient cannot do), please initial here",
          "if your patient has current restrictions (activities patient should not do) and/or limitations (activities patient cannot do) list below",
          "please provide the duration of these restrictions and limitations. from (mm/dd/yy)",
          "to (mm/dd/yy)",
          "d. signature of attending physician",
          "physician name (last name, first name, mi, suffix) please print",
          "degree/specialty",
          "address",
          "city",
          "state",
          "zip",
          "telephone number",
          "fax number",
          "physician tax id number",
          "are you related to the patient?",
          "if yes, what is the relationship?",
          "signature of physician",
          "date",
          "attending physician statement (please print)",
          "to be completed by physician or treating provider",
          "name of patient (last name, suffix, first name, mi)",
          "social security number",
          "date of birth (mm/dd/yy)",
          "patient telephone number",
          "employer name",
          "a. complete this section for pregnancy, then go to section c",
          "expected delivery date (mm/dd/yy)",
          "actual delivery date (mm/dd/yy)",
          "delivery type",
          "date of first visit for this pregnancy (mm/dd/yy)",
          "date hospitalized (mm/dd/yy)",
          "diagnosis",
          "icd code",
          "did you advise your patient to stop working?",
          "if yes, on what date (mm/dd/yy)?",
          "were these any complications causing your patient to stop working prior to her expected delivery date?",
          "if yes, please explain",
          "b. complete this section for all conditions except pregnancy, then go to section c",
          "date of first visit for this current condition(s) (mm/dd/yy)",
          "date of last office visit (mm/dd/yy)",
          "date of next office visit (mm/dd/yy)",
          "did you advise your patient to stop working?",
          "if yes, on what date (mm/dd/yy)?",
          "has the patient been treated for the same/similar condition in the past?",
          "if yes, please provide treatment dates (mm/dd/yy)",
          "from",
          "through",
          "is the patient's condition work related?",
          "patient height",
          "patient's weight",
          "primary diagnosis",
          "primary icd code",
          "secondary diagnosis",
          "secondary icd code",
          "has the patient been hospitalized?",
          "if yes, date hospitalized (mm/dd/yy)",
          "through (mm/dd/yy)",
          "was surgery performed?",
          "if yes, what procedure was performed?",
          "cpt code",
          "date surgery performed (mm/dd/yy)",
          "what is your treatment plan? please include all medications.",
          "attending physician statement (please print)",
          "part i: to be completed by patient",
          "name of patient (last name, suffix, first name, mi",
          "social security number",
          "home telephone number",
          "employer telephone number",
          "part ii: to be completed by physician or treating provider",
          "a. complete this section for pregnancy, then go to section c",
          "expected delivery date (mm/dd/yy)",
          "actual delivery date (mm/dd/yy)",
          "delivery type",
          "date of first visit for the pregnancy (mm/dd/yy)",
          "date hospitalized (mm/dd/yy)",
          "diagnosis",
          "icd code",
          "did you advice your patient to stop working?",
          "if yes, on what date (mm/dd/yy)?",
          "were there any complications causing your patient to stop working prior to her expected delivery date?",
          "if yes, please explain",
          "b. complete this section for all conditions except pregnancy, then go to sextion c",
          "date of first visit for the current condition(s) (mm/dd/yy)",
          "date of last office visit (mm/dd/yy)",
          "date of next office visit (mm/dd/yy)",
          "did you advice your patient to stop working?",
          "if yes, on what date (mm/dd/yy)?",
          "has the patient been treated for the same/similar condition in the past?",
          "if yes, please provide treatment dates (mm/dd/yy)",
          "from",
          "through",
          "is the patient's condition work related?",
          "patient's height",
          "patient's weight",
          "primary diagnosis",
          "primary icd code",
          "secondary diagnosis",
          "secondary icd code",
          "has the patient been hospitalized",
          "if yes, date hospitalized (mm/dd/yy)",
          "through (mm/dd/yy)",
          "was surgery performed",
          "if yes, what procedure was performed?",
          "cpt code",
          "date surgery performed (mm/dd/yy)",
          "what is your treatment plan? please include all medications",
          "employee statement (please print)",
          "a. information about you",
          "last name",
          "suffix",
          "first name",
          "mi",
          "date of birth (mm/dd/yy)",
          "social security number",
          "gender",
          "the state in which you work",
          "home address",
          "city",
          "state",
          "zip",
          "telephone number where we can reach you",
          "preferred email address (for confirmation purposes only)",
          "employer name",
          "language preference",
          "please check all types of coverage you have with unum",
          "are you currently self-employed?",
          "do you work for another employer?",
          "if yes, employer name",
          "telephone number",
          "b. information about your disability",
          "what is your expected delivery date?",
          "if you have delivered, what was your delivery date?(mm/dd/yy)",
          "what type of delivery?",
          "were there any complications causing you to stop work prior to your expected delivery date?",
          "if yes, please explain",
          "2. for other than pregnancy, is your disability caused by",
          "what is the name of your medical condition?",
          "date you were first treated by a physician (mm/dd/yy)",
          "if related to an injury, when, where and how did the injury occur?",
          "3. is your condition work related?",
          "if yes, have you filed a workers' compensation claim?",
          "if yes, please explain how the work related injury/illness occured",
          "4. have you been hospitalized?",
          "if yes, date hospitalized (mm/dd/yy)",
          "through (mm/dd/yy)",
          "5. last day you were at work (mm/dd/yy)",
          "number of hours worked on date last worked",
          "first date you missed work due to this medical condition (mm/dd/yy)",
          "6. have you returned to work?",
          "part time (mm/dd/yy)",
          "if yes, indicate date below",
          "part-time hours per week",
          "full time (mm/dd/yy)",
          "if you have not returned to work, when do you expect to return?",
          "part time (mm/dd/yy)",
          "part-time hours per week",
          "full time (mm/dd/yy)",
          "unknown",
          "c. information about your medical providers",
          "provider name",
          "telephone no.",
          "fax no.",
          "date of first visit for this condition (mm/dd/yy)",
          "date of next visit for this condition (mm/dd/yy)",
          "insured's signature",
          "date signed",
          "printed name",
          "social security number",
          "i signed on behalf of the insured as",
          "attending physician statement (continued)",
          "date of birth",
          "have you advised the patient to work?",
          "expected return to work date (mm/dd/yy)",
          "full time",
          "part time",
          "part-time hours per day",
          "current restrictions (activities patient should not do) and current limitations (activities patient cannot do). please be specific and understand tht a reply of \"no work\" or \"totally incapacitated\" will not enable us to evaluate the claim for benefits",
          "what diagnostic or clinical findings support your patient's work restrictions and limitations?",
          "c. signature of attending physician",
          "physician name (last name, first name, mi, suffix) please print",
          "degree/specialty",
          "address",
          "city",
          "state",
          "zip",
          "telephone number",
          "fax number",
          "physician tax id number",
          "are you related to the patient?",
          "if yes, what is the relationship?",
          "signature of physician",
          "date",
          "employee name (last name, suffix, first name, mi)",
          "date of birth (mm/dd/yy)",
          "federal income tax",
          "if yes, how much do you want withhold from each check? (whole dollar amount) $",
          "state income tax",
          "if yes, how much do you want without from each check? (whole dollar amount) $",
          "signature",
          "date",
          "insured's signature",
          "date signed",
          "printed name",
          "social security number",
          "i signed on behalf of the insured as",
          "attending physician or provider of service statement (continued)",
          "patient's name (last name, suffix, first name, mi)",
          "date of birth (mm/dd/yy)",
          "d. complete this section for inpatient/outpatient surgery claims (please refer to place of service codes above)",
          "e. signature of attending physician or provider of service",
          "physician name (last name, first name, mi, suffix) please print",
          "medical specialty",
          "degree",
          "address",
          "city",
          "state",
          "zip",
          "telephone number",
          "fax number",
          "physician's tax id number",
          "are you related to the patient?",
          "if yes, what is the relationship?",
          "physician signature",
          "date",
          "attending physician or provider of service statement (please print)",
          "to be completed by attending physician or treating provider",
          "please provide copies of all test results, operative reports, pathology reports, and/or your detailed medical statement related to the service provided to the patient.",
          "patient name (last name, suffix, first name, mi)",
          "patient gender",
          "patient social security number",
          "patient date of birth (mm/dd/yy)",
          "a. complete this section for all medical conditions",
          "date of injury of first symptom (mm/dd/yy)",
          "date patient first consulted you for this condition (mm/dd/yy)",
          "diagnosis",
          "icd code",
          "has the patient been treated for the same or a similar condition by any physician in the past?",
          "if yes, what was the first date of treatment (mm/dd/yy)?",
          "b. complete this section for diagnostic testing claims",
          "diagnosis/icd codes",
          "diagnostic procedure date (mm/dd/yy)",
          "diagnostic procedure codes/description",
          "(if the patient received multiple tests, please provide dates and locations in an attached doument)",
          "place of service codes",
          "c. complete this section for emergency room and/or hospital/icu confinement claims (please refer to place of service codes above)",
          "insured's signature",
          "date signed",
          "printed name",
          "social security number",
          "i signed on behalf of the insured as",
          "attending physician statement (continued)",
          "patient's name (last name, first name, mi, suffix)",
          "date of birth (mm/dd/yy)",
          "return to work assessment",
          "have you advised the patient to return to work?",
          "if yes, expected return to work date (mm/dd/yy)",
          "hours per day",
          "current restrictions (activities patient should not do)",
          "current limitations (activities patient cannot do)",
          "do you support your patient's return to work within the restrictions and limitations you provided?",
          "if yes, as of (mm/dd/yy)",
          "if no, when do you expect improvement in the patient's functional capacity?",
          "c. signature of attending physician",
          "physician name (last name, first name, mi, suffix) please print",
          "medical specialty",
          "degree",
          "address",
          "city",
          "state",
          "zip",
          "telephone number",
          "fax number",
          "physician's tax id number",
          "are you related to this patient?",
          "if yes, what is the relationship?",
          "signature of physician",
          "date",
          "employee statement (continued)",
          "employee/individual's name (last name, suffix, first name, mi)",
          "date of birth (mm/dd/yy)",
          "signature",
          "date",
          "attending physician statement (continued)",
          "patient's name (last name, suffix, first name, mi)",
          "date of birth (mm/dd/yy)",
          "treatment",
          "what is your treatment plan?",
          "when do you expect the patient to return to work?",
          "medications (please attach medication log)",
          "has the patient been hospitalized?",
          "if yes, date hospitalized (mm/dd/yy):",
          "through (mm/dd/yy)",
          "facility name",
          "address",
          "city",
          "was surgery performed?",
          "if yes, what procedure was performed?",
          "date surgery performed (mm/dd/yy)",
          "is the patient still under your care?",
          "if no, final date of treatment",
          "my spouse",
          "(name)",
          "other family member",
          "(name / relationship)",
          "other person",
          "(name / relationship)",
          "i authorize unum to leave message about my claim on my voicemail / answering machine.",
          "insured's signature",
          "date",
          "Printed name",
          "social security number",
          "i signed on behalf of the claimant as",
          "attending physician statement (please print)",
          "part i: to be completed by patient",
          "name of patient (last name, suffix, first name, mi)",
          "date of birth (mm/dd/yy)",
          "social security number",
          "home telephone number",
          "cellular telephone number",
          "part ii: to be completed by physician or treating provider",
          "a. complete this section for normal pregnancy, then go to section c",
          "expected delivery date (mm/dd/yy)",
          "actual delivery date (mm/dd/yy)",
          "delivery type",
          "date of first visit for this pregnancy (mm/dd/yy)",
          "date hospitalized (mm/dd/yy)",
          "did you advise your patient to stop working?",
          "if yes, on what date (mm/dd/yy)?",
          "b. complete this section for all conditions except normal pregnancy",
          "patient information",
          "height",
          "weight",
          "date of visit for this current condition(s)(mm/dd/yy)",
          "did you advise your patient to stop working?",
          "if yes, on what date (mm/dd/yy)?",
          "has the patient been treated for the same/similar condition in the past?",
          "if yes, please provide treatment dates (mm/dd/yy):",
          "from",
          "through",
          "is the patient's condition due to injury or sickness involving the patient's employment?",
          "diagnosis",
          "what is the primary diagnosis preventing the patient from working?",
          "please include primary icd-9 or dsm-iv multi-axial diagnosis codes",
          "icd-9",
          "dsm-iv i",
          "ii",
          "iii",
          "iv",
          "v",
          "what are the other conditions that prevent the patient from working?",
          "secondary diagnosis",
          "icd-9",
          "secondary diagnosis:",
          "icd-9:",
          "are there any cognitive deficits or psychiatric conditions that impact function?",
          "if yes, please provide restrictions and limitations:",
          "date of last examination (mm/dd/yy):",
          "date of next examination (mm/dd/yy):",
          "what symptoms is your patient reporting about his/her condition?",
          "what diagnostic or clinical findings support your diagnosis?",
          "what diagnostic or clinical findings support your patient's work restrictions and limitations?",
          "insured/patient statement (please print)",
          "a. type of claim",
          "please check the type of claim you are filing",
          "this claim is for",
          "b. information about the insured",
          "last name",
          "suffix",
          "first name",
          "mi",
          "date of birth (mm/dd/yy)",
          "social security number",
          "gender",
          "home address",
          "city",
          "state",
          "zip",
          "home telephone number",
          "cellular telephone number",
          "work telephone number",
          "accident policy number",
          "preferred e-mail address (for confirmation purposes only)",
          "language preference",
          "please check all types of coverage you have with unum.",
          "short term disability",
          "policy #",
          "long term disability",
          "individual disability",
          "life insurance",
          "voluntary benefits disability",
          "voluntary benefits cancer/critical illness insurance",
          "voluntary benefits medsupport insurance",
          "c. information about the patient",
          "last name",
          "suffix",
          "first name",
          "mi",
          "date of birth (mm/dd/yy)",
          "social security number",
          "gender",
          "home address",
          "city",
          "state",
          "zip",
          "if claim is for a child, please state your relationship to the child",
          "d. complete this section for hospital confinement/intensive care claims.",
          "please attach an itemized copy of your hospital bill that includes the following information. diagnosis, admission and discharge dates, name of facility and address.",
          "if your hospital bill does not contain this information, please ask your doctor to complete the attending physician statement (pages 8-10 of this form.)",
          "attending physician statement (continued)",
          "insured's name (last name, first name, mi, suffix)",
          "date of birth (mm/dd/yy)",
          "patient's name (last name, first name, mi, suffix)",
          "date of birth (mm/dd/yy)",
          "c. complete this section for hospital confinement/intensive care benefit claims.",
          "has the patient been hospitalized?",
          "if yes, date hospitalized (mm/dd/yy)",
          "through (mm/dd/yy)",
          "facility name",
          "address",
          "city",
          "state",
          "zip",
          "was surgery performed?",
          "if yes, what procedure was performed?",
          "date surgery performed (mm/dd/yy)",
          "is the patient still under your care?",
          "if no, final date of treatment (mm/dd/yy)",
          "diagnosis",
          "icd code",
          "dates of inpatient hospital confinement",
          "from (mm/dd/yy)",
          "to (mm/dd/yy)",
          "dates of confinement in intensive care, including coronary care unit:",
          "from (mm/dd/yy)",
          "to (mm/dd/yy)",
          "hospital name",
          "telephone number",
          "hospital address",
          "date of surgery (mm/dd/yy)",
          "surgical procedure",
          "cpt code:",
          "date of follow up visit following confinement or outpatient surgery",
          "c. signature of attending physician",
          "physician name (last name, first name, mi, suffix) please print",
          "medical specialty",
          "degree",
          "address",
          "city",
          "state",
          "zip",
          "telephone number",
          "fax number",
          "physician's tax id number:",
          "are you related to this patient?",
          "if yes, what is the relationship?",
          "physician signature",
          "date",
          "my spouse",
          "(name)",
          "(telephone number)",
          "other family member:",
          "(name / relationship)",
          "(telephone number)",
          "other person",
          "(name / relationship)",
          "(telephone number)",
          "i authorize unom to leave messages about my claim on my voicemail / answering machine.",
          "insured/patient signature",
          "date",
          "printed name",
          "social security number",
          "i signed on behalf of the claimant as",
          "attending physician statement (please print)",
          "part i: to be completed by insured/patient",
          "insured name (last name, suffix, first name, mi)",
          "insured social security number",
          "patient name (last name, suffix, first name, mi)",
          "patient social security number",
          "patient relationship to insured:",
          "patient gender:",
          "patient date of birth (mm/dd/yy)",
          "part ii: to be completed by attending physician or treating provider",
          "a. complete this section for accident claims only.",
          "diagnosis",
          "icd code",
          "date first unable to work (mm/dd/yy)",
          "date of first visit for this current condition(s) (mm/dd/yy)",
          "is this condition to result of an accidental injury?",
          "if related to a fracture or dislocation, please indicate:",
          "if related to a laceration. please indicate the length:",
          "if related to a burn. please indicate the degree:",
          "mri",
          "date: (mm/dd/yy)",
          "is the patient's condition related to his/her employment?",
          "b. complete this section for disability claims only.",
          "if this claim is related to normal pregnancy, please provide the following:",
          "expected delivery date: (mm/dd/yy)",
          "actual delivery date: (mm/dd/yy)",
          "date first unable to work (mm/dd/yy)",
          "delivery type:",
          "has the patient been treated for the same or a similar condition by another physician in the past?",
          "if yes, please list the diagnosis and treatment dates (mm/dd/yy).",
          "has the patient received any chiropractic, physical, occupational and/or speech therapy?",
          "if yes, please provide dates of treatment:",
          "is the patient's condition related to his/her employment?",
          "have you advised the patient to return to work?",
          "if yes, expected return to work date (mm/dd/yy):",
          "hours per day",
          "if yes, please indicate any ongoing restrictions and limitations in the space provided below.",
          "if no, please indicate the restrictions and limitations that prevent the patient from returning to work in the space provided below.",
          "current restrictions (activities patient should not do)",
          "current limitations (activities patient cannot do)",
          "is the patient permanently disabled?",
          "if yes what is the recommended frequency of treatment?",
          "does the patient have permanent restrictions and limitations?",
          "if yes, please list the permanent restrictions and limitations.",
          "insured/patient statement (continued)",
          "insured's name (last name, suffix, first name, mi)",
          "date of birth (mm/dd/yy)",
          "e. complete this section for accidental injury claims",
          "date of accident",
          "time of accident",
          "were you at work at the time of your accident?",
          "was this a motor vehicle accident?",
          "please explain how your accident happened. (if you need more space, please attach a separate sheet of paper).",
          "f. information about physicians and hospitals",
          "primary care physician name",
          "mailing address",
          "telephone no.",
          "specialty",
          "city",
          "state",
          "zip",
          "fax no.",
          "date of first visit (mm/dd/yy)",
          "date of next visit (mm/dd/yy)",
          "treating physician name",
          "mailing address",
          "telephone no.",
          "specialty",
          "city",
          "state",
          "zip",
          "fax no.",
          "date of first visit (mm/dd/yy)",
          "date of next visit (mm/dd/yy)",
          "treating physician name",
          "mailing address",
          "telephone no.",
          "specialty",
          "city",
          "state",
          "zip",
          "fax no.",
          "date of first visit (mm/dd/yy)",
          "date of next visit (mm/dd/yy)",
          "hospital",
          "address",
          "date of visit/admission (mm/dd/yy)",
          "procedure",
          "city",
          "state",
          "zip",
          "date of discharge (mm/dd/yy)",
          "hospital",
          "address",
          "date of visit/admission (mm/dd/yy)",
          "procedure",
          "city",
          "state",
          "zip",
          "date of discharge (mm/dd/yy)",
          "insured/patient statement (continued)",
          "insured's name (last name, suffix, first name, mi)",
          "date of birth (mm/dd/yy)",
          "h. signature of insured",
          "signature",
          "date",
          "i signed on behalf of the insured, as",
          "insured's signature",
          "date signed",
          "printed name",
          "social security number",
          "i signed on behalf of the insured as",
          "(claimant signature)",
          "(date signed)",
          "(print name)",
          "(social security number)",
          "i signed on behalf of claimant as",
          "insured's signature",
          "date signed",
          "printed name",
          "social security number",
          "i signed on behalf of the insured as",
          "attending physician statement (please print)",
          "to be completed by physician or treating provider",
          "name of patient (last name, suffix, first name, mi)",
          "social security number",
          "date of birth (mm/dd/yy)",
          "patient telephone number",
          "employer name",
          "a. complete this section for pregnancy, then go to section c",
          "expected delivery date (mm/dd/yy)",
          "actual delivery date(mm/dd/yy)",
          "delivery type",
          "date of first visit for this pregnancy (mm/dd/yy)",
          "date hospitalized (mm/dd/yy)",
          "diagnosis",
          "icd code",
          "did you advise your patient to stop working?",
          "if yes, on what date (mm/dd/yy)?",
          "were these any complications causing your patient to stop working prior to her expected delivery date?",
          "if yes, please explain",
          "b. complete this section for all conditions except pregnancy, then go to section c",
          "date of first visit for this current condition(s) (mm/dd/yy)",
          "date of last office visit (mm/dd/yy)",
          "date of next office visit (mm/dd/yy)",
          "did you advise your patient to stop working?",
          "if yes, on what date (mm/dd/yy)?",
          "has the patient been treated for the same/similar condition in the past?",
          "if yes, please provide treatment dates (mm/dd/yy)",
          "from",
          "through",
          "is the patient's condition work related?",
          "patient height",
          "patient's weight",
          "primary diagnosis",
          "primary icd code",
          "secondary diagnosis",
          "secondary icd code",
          "has the patient been hospitalized?",
          "if yes, date hospitalized (mm/dd/yy)",
          "through (mm/dd/yy)",
          "was surgery performed?",
          "if yes, what procedure was performed?",
          "cpt code",
          "date surgery performed (mm/dd/yy)",
          "what is your treatment plan? please include all medications.",
          "attending physician statement (continued)",
          "patient name (last name, first name, mi, suffix)",
          "date of birth (mm/dd/yy)",
          "other providers: are you aware or have you referred your patient to other treating providers? if yes, please provide complete name, contact information and specialty of any other treating physicians",
          "have you advised the patient to return to work?",
          "expected return to work date (mm/dd/yy)",
          "part-time hours per day",
          "c. functional capacity",
          "(activities patient cannot do), please initial here",
          "if your patient has current restrictions (activities patient should not do) and/or limitations (activities patient cannot do) list below.",
          "please provide the duration of these restrictions and limitations.",
          "from (mm/dd/yy)",
          "to (mm/dd/yy)",
          "d. signature of attending physician",
          "physician name (last name, first name, mi, suffix) please print",
          "degree/specialty",
          "address",
          "city",
          "state",
          "zip",
          "telephone number",
          "fax number",
          "physician tax id number",
          "are you related to the patient?",
          "if yes, what is the relationship?",
          "signature of physician",
          "date",
          "employee name",
          "employee ssn",
          "section 4: employee (applicant) statements",
          "employee (applicant) signature",
          "date (mm/dd/yyyy)",
          "employee (applicant) signature",
          "date (mm/dd/yyyy)",
          "application type",
          "section 1: employee (applicant) information - always complete",
          "employee name (first, middle, last)",
          "social security number",
          "home address (street/po box)",
          "gender",
          "city",
          "date of birth (mm/dd/yyyy)",
          "state",
          "zip code",
          "home phone #",
          "employee id/payroll #",
          "employer name",
          "customer number",
          "date of hire (mm/dd/yyyy)",
          "st/po box",
          "occupation",
          "city",
          "state",
          "zip code",
          "work phone #",
          "are you actively at work?",
          "scheduled number of work hours/week",
          "primary beneficiary",
          "relationship",
          "contingent beneficiary",
          "relationship",
          "section 2: spouse information - complete only if applying for spouse coverage",
          "name (first, middle, last)",
          "social security number",
          "gender",
          "does the spouse live in the u.s.?",
          "date of birth (mm/dd/yyyy)",
          "if \"no, \" is your spouse a u.s. citizen?",
          "primary beneficiary",
          "relationship",
          "contingent beneficiary",
          "relationship",
          "section 3: coverage information",
          "group accident",
          "cost per pay period",
          "total cost per pay period",
          "application type",
          "section 1: employee (applicant) information - always complete",
          "employee name (first, middle, last)",
          "social security number",
          "home address (street/po box)",
          "gender",
          "city",
          "date of birth (mm/dd/yyyy)",
          "state",
          "zip code",
          "home phone #",
          "employee id/payroll #",
          "employer name",
          "customer number",
          "date of hire (mm/dd/yyyy)",
          "st/po box",
          "occupation",
          "city",
          "state",
          "zip code",
          "work phone #",
          "are you actively at work?",
          "scheduled number of work hours/week",
          "primary beneficiary",
          "relationship",
          "contingent beneficiary",
          "relationship",
          "section 2: spouse information - complete only if applying for spouse coverage",
          "name (first, middle, last)",
          "social security number",
          "gender",
          "does the spouse live in the u.s.?",
          "date of birth (mm/dd/yyyy)",
          "if \"no, \" is your spouse a u.s. citizen?",
          "primary beneficiary",
          "relationship",
          "contingent beneficiary",
          "relationship",
          "section 3: coverage information",
          "group accident",
          "cost per pay period",
          "employer selected benefit[s]",
          "[optional Employee selected benefit]",
          "total cost per pay period",
          "please check the type of claim you are filing below",
          "this claim is for",
          "section a. general information",
          "employee/policyholder information",
          "name of employee/policyholder",
          "social security number",
          "date of birth",
          "address (street, apt. #, city, state, zip)",
          "home phone number",
          "work phone number",
          "fax number",
          "email address",
          "employer name and address",
          "patient information",
          "name of patient (if not self)",
          "social security number",
          "date of birth",
          "address (street, apt. #, city, state, zip)",
          "home phone number",
          "work phone number",
          "fax number",
          "email address",
          "employer name and address",
          "information about your doctor(s) and/or hospital (please print)",
          "full name of treating doctor",
          "specialty",
          "mailing address (street, city, state, zip)",
          "phone number",
          "fax number",
          "full name of primary doctor",
          "specialty",
          "mailing address (street, city, state, zip)",
          "phone number",
          "fax number",
          "full name of referring doctor/hospital",
          "specialty",
          "mailing address (street, city, state, zip)",
          "phone number",
          "fax number",
          "certification",
          "policyholder/employer's name",
          "social security number",
          "date",
          "patient signature",
          "policyholder/employee signature",
          "patient name",
          "social security number",
          "section b. accidental injury",
          "date of accident",
          "time of accident",
          "tell us how your accident happened: (if you need more space, you may attach oa separate place pf paper.)",
          "were you at work (working for wage or profit) at the time of your accident?",
          "section c. hospital confinement, intensive care benefit",
          "diagnosis/icd-9 code",
          "dates of inpatient hospital confinement: from",
          "to",
          "dates of confinement in intensive care, including coronary care unit: from",
          "to",
          "hospital",
          "phone number",
          "hospital address",
          "date of surgery",
          "procedure/procedure code",
          "date of office visit following confinement or outpatient surgery",
          "signature of doctor",
          "date",
          "name of doctor",
          "phone number",
          "specialty",
          "fax number",
          "address",
          "tax id or ssn",
          "insured/patient statement (please print)",
          "a. type of claim",
          "please check the type of claim you are filing",
          "this claim is for",
          "b. information about the insured/policyholder",
          "last name",
          "suffix",
          "first name",
          "mi",
          "date of birth (mm/dd/yy)",
          "social security number",
          "gender",
          "home address",
          "city",
          "state",
          "zip",
          "home telephone number",
          "cellular telephone number",
          "work telephone number",
          "accident policy number",
          "preferred e-mail address (for confirmation purposes only)",
          "language preference",
          "if known, please check all types of coverage you have with unum.",
          "c. information about the patient (if different from insured/policyholder) check one",
          "last name",
          "suffix",
          "first name",
          "mi",
          "date of birth (mm/dd/yy)",
          "social security number",
          "gender",
          "relationship to insured/policyholder (check one)",
          "if claim is for a child, please state your relationship to the child",
          "d. information about your condition",
          "date of accident",
          "time of accident",
          "please explain how your accident happened. (if you need more space, please attach a separate sheet of paper).",
          "were you at work at the time of your accident?",
          "if yes, have you received workers' compensation benefits for your occupational injury?",
          "is your claim pending a workers' compensation decision?",
          "have you stopped working?",
          "if yes, what was the last day that you worked? (mm/dd/yy)",
          "was this a motor vehicle accident?",
          "diagnosis",
          "confinement dates:(mm/dd/yy)",
          "to (mm/dd/yy)",
          "attending physician statement",
          "insured/policyholder name (last name, first name, mi, suffix)",
          "date of birth",
          "patient name (last name, first name, mi, suffix)",
          "date of birth (mm/dd/yy)",
          "accident details",
          "is this condition the result of an accident injury",
          "if yes, date of accident (mm/dd/yy)",
          "is this condition the result of his/her employment",
          "has the patient been treated for the same or a similar condition by another physician in the past?",
          "if yes, please provide the following",
          "diagnosis",
          "treatment dates",
          "did you advice the patient to stop working?",
          "if yes, as of what date? (mm/dd/yy)",
          "if this claim is related to normal pregnancy, please provide the following",
          "expected delivery date (mm/dd/yy)",
          "actual delivery date (mm/dd/yy",
          "c. signatue of attending physician",
          "physician name (last name, first name, mi, suffix) please print",
          "medical specialty",
          "degree",
          "address",
          "city",
          "state",
          "zip",
          "telephone number",
          "fax number",
          "physician's tax id number",
          "are you related to this patient?",
          "if yes, what is the relationship",
          "physician signature",
          "date",
          "insured's name (last name, suffix, first name, mi)",
          "date of birth (mm/dd/yy)",
          "e. information about physician",
          "treating physician name",
          "treating physician telephone number",
          "signature",
          "date",
          "i signed on behalf of the insured, as",
          "my spouse",
          "(name)",
          "(telephone number)",
          "other family member",
          "(name/relationship)",
          "(telephone number)",
          "other person",
          "(name/relationship)",
          "(telephone number)",
          "i authorize unum to leave message about my claim on my voicemail/answering machine.",
          "insured/patient signature",
          "date",
          "printed name",
          "social security number",
          "i signed on behalf of the claimant as",
          "av order / other",
          "diagnosis remarks",
          "supplies/casting order",
          "next oppointment",
          "ain mgmt w/",
          "ient referral",
          "country",
          "date of visit/admission",
          "date of discharge",
          "procedure",
          "Employer Name",
          "signed date",
          "electronically signed indicator",
          "policy number",
          "claim event identifier",
          "submission date",
          "Client:",
          "Policy Number:",
          "Policy Type:",
          "ID Number:",
          "Address Details:",
          "Branch:",
          "Agent/Insp:",
          "Postal",
          "Risk",
          "Inception Date",
          "Address:",
          "Previous Insurer:",
          "Address:",
          "Account Holder:",
          "Account Number:",
          "Bank Name:",
          "Tel (H):",
          "Tel (W):",
          "Cellular No:",
          "Fax:",
          "Email Address:",
          "Policy Endorsements:",
          "SOS Services:",
          "Other Details:",
          "Banking Details:",
          "Contact Details",
          "city",
          "state",
          "zip",
          "fax",
          "social security number",
          "home telephone number",
          "cellular telephone number",
          "work phone #",
          "bank/financial institution information",
          "personal account number",
          "policy #",
          "tax id",
          "st/po box",
          "hospital",
          "hospital address",
          "Banking Details"
          ]

print("original fields", len(fields))
fields = list(map(lambda item: item.strip().lower(), fields))
fields = set(fields)
print("unique fields", len(fields))

fields_containing_dates = set()
fields_containing_compound_names = set()  # perfect
fields_containing_names = set()
fields_containing_SSN = set()
fields_containing_gender = set()
fields_containing_mail = set()
fields_containing_fax = set()
fields_containing_tele = set()
fields_containing_addresses = set()  # perfect
fields_containing_icd = set()  # perfect
fields_containing_MI = set()
fields_containing_zip = set()
fields_containing_yes_no = set()
fields_containing_signature = set()  # leave me
fields_containing_mailing_address = set()
fields_containing_state = set()
fields_containing_city = set()
fields_containing_tax_id = set()
fields_containing_hospitals = set()
fields_containing_num_hours = set()  # perfect
fields_containing_length_height_weight = set()  # perfect
fields_containing_relation = set()  # perfect
fields_containing_burn_deg = set()  # perfect
fields_containing_when = set()  # perfect
fields_containing_numbers = set()  # perfect
fields_containing_diag = set()

fields_descriptive = set()  # perfect
fields_containing_name_word = set()
fields_containing_date_word = set()

tryme = set()
for field in fields.copy():
    withins = re.findall(r'(?<=\()(.+?)(?=$)', field)
    score = 0
    if len(withins) > 0:
        for within in withins:
            score = max(score, int("last" in within) + int("first" in within) + int("mi" in within) + int("suffix" in within) + int("middle" in within))
    if "(mm/dd/yy" in field or "(mm/dd/yyyy)" in field:
        fields_containing_dates.add(field)
        fields.remove(field)
    elif score > 1:
        fields_containing_compound_names.add(field)
        fields.remove(field)
    elif "date" in field:
        fields_containing_date_word.add(field)
        fields.remove(field)
    elif "name" in field:
        fields_containing_name_word.add(field)
        fields.remove(field)
    elif "social security" in field or "ssn" in field:
        fields_containing_SSN.add(field)
        fields.remove(field)
    elif "gender" in field:
        fields_containing_gender.add(field)
        fields.remove(field)
    elif "icd" in field:
        fields_containing_icd.add(field)
        fields.remove(field)

    # elif "mi" in field:
    #     fields_containing_MI.add(field)
    #     fields.remove(field)

# print("\n".join(fields_containing_SSN))
# exit()
for field in fields_containing_dates.copy():
    normalized = re.sub("\(mm/dd/yy\)|\(mm/dd/yy|\"\(mm/dd/yyyy\)", "", field)
    for candidate_date in fields_containing_date_word.copy():
        if normalized.strip() in candidate_date and len(candidate_date) < len(normalized.strip()) + 20:
            fields_containing_dates.add(candidate_date)
            fields_containing_date_word.remove(candidate_date)


def transfer_list(source_set, dist_set, list_of_fields):
    for manual_date in list_of_fields:
        manual_date = manual_date.lower().strip()
        assert manual_date in source_set
        # try:
        #     assert manual_date in source_set
        # except Exception as e:
        #     print()
        if manual_date in source_set:
            source_set.remove(manual_date)
            dist_set.add(manual_date)


transfer_list(fields_containing_date_word, fields_containing_dates, ["inception date", "signed date", "(date signed)", "date signed", "if yes, indicate date below", "effective date", "if yes, please provide dates of treatment:", "final date of treatment", "date of follow up visit following confinement or outpatient surgery", "dates of confinement in intensive care, including coronary care unit: from", "b) date of first visit regarding current condition?", "c) date patient caused work beacuse of condition?", "submission date", "date", "treatment dates", "dates of inpatient hospital confinement: from", "dates of confinement in intensive care, including coronary care unit:", "date of accident", "date of office visit following confinement or outpatient surgery", "b) date of last examination"])
fields = set.union(fields, fields_containing_date_word)

transfer_list(fields, fields_containing_mail, ["preferred email address (for confirmation purposes only)", "email address", "email address:", "preferred e-mail address (for confirmation purposes only)", ])
transfer_list(fields, fields_containing_names, ["my spouse:", "my spouse", "suffix"])
transfer_list(fields, fields_containing_fax, ["fax:", "fax number", "fax", "fax no."])
transfer_list(fields, fields_containing_dates, ["to"])
transfer_list(fields, fields_containing_MI, ["mi"])
transfer_list(fields, fields_containing_signature, ["c. signatue of attending physician", "e. signature of attending physician or provider of service", "signature of physician", "employee (applicant) signature", "insured's signature", "h. signature of insured", "d. signature of individual", "patient signature", "insured/patient signature", "signature of individual", "claimant signature", "physician signature", "(claimant signature)", "signature", "d. signature of attending physician", "signature of doctor", "policyholder/employee signature", "c. signature of attending physician", ])
transfer_list(fields, fields_containing_tele, ["cellular no:", "work phone #", "home phone #", "home phone number", "phone number", "work phone number", "tel (w):", "tel (h):", "(telephone number)", "home telephone number", "telephone number", "telephone number where we can reach you", "telephone no.", "patient telephone number", "cellular telephone number", "employer telephone number", "work telephone number", "treating physician telephone number"])
transfer_list(fields, fields_containing_zip, ["zip", "zip code"])
transfer_list(fields, fields_containing_yes_no,
              ["has the patient been hospitalized", "e) has the patient been treated for the same/similar condition in the past?", "d) was surgery performed? cpt 4 code(s)", "has the patient received any chiropractic, physical, occupational and/or speech therapy?", "has the patient been treated for the same or a similar condition by any physician in the past?", "i authorize unum to leave message about my claim on my voicemail/answering machine.", "has the patient been treated for the same or a similar condition by another physician in the past?", "has the patient been treated for the same/similar condition in the past?", "has the patient been hospitalizes?", "if yes, have you received workers' compensation benefits for your occupational injury?", "i authorize unom to leave messages about my claim on my voicemail / answering machine.", "i authorize unum to leave message about my claim on my voicemail / answering machine.", "c) has patient been hospitalized?",
               "f) is the patient's condition due to injury or sickness involving the patient's employment?", "if \"no, \" is your spouse a u.s. citizen?",
               "3. is your condition work related?",
               "6. have you returned to work?", "has the patient been hospitalized?", "if yes, have you filed a workers' compensation claim?", "were these any complications causing your patient to stop working prior to her expected delivery date?",
               "were there any complications causing your patient to stop working prior to her expected delivery date?", "were you at work at the time of your accident?",
               "were you at work (working for wage or profit) at the time of your accident?",
               "were there any complications causing you to stop work prior to your expected delivery date?", "d) did you advise patient to cease work?", "did you advice your patient to stop working?", "do you work for another employer?",
               "do you support your patient's return to work within the restrictions and limitations you provided?", "does the spouse live in the u.s.?", "does the patient have permanent restrictions and limitations?", "have you advised the patient to return to work?",
               "have you advise the patient to return to work?", "have you advised the patient to work?", "e) is the patient still under your care?", "4. have you been hospitalized?", "have you stopped working?", "was this a motor vehicle accident?", "was surgery performed?", "was surgery performed", "did you advice the patient to stop working?", "did you advise your patient to stop working?", "is the patient's condition due to injury or sickness involving the patient's employment?", "is the patient permanently disabled?", "is this condition to result of an accidental injury?", "is your claim pending a workers' compensation decision?", "is this condition the result of an accident injury", "is the patient still under your care?", "is the patient's condition related to his/her employment?", "is the patient's condition work related?", "is this condition the result of his/her employment", "are you currently self-employed?",
               "are you, the physician, related to this patient?", "are you related to this patient?", "are you actively at work?", "are you related to the patient?", "are there any cognitive deficits or psychiatric conditions that impact function?", ])

transfer_list(fields, fields_containing_mailing_address, ["mailing address", "mailing address (street, city, state, zip)", ])
transfer_list(fields, fields_containing_state, ["the state in which you work", "state", ])
transfer_list(fields, fields_containing_tax_id, ["tax id", "physician's tax id number:", "physician tax id number", "physician's tax id number", ])
transfer_list(fields, fields_containing_city, ["city", ])
transfer_list(fields, fields_containing_num_hours, ["part-time hours per week", "hours per day", "a) patient's ability to: (please check number of hours per workday and how often)", "scheduled number of work hours/week", "part-time hours per day", "number of hours worked on date last worked", ])
transfer_list(fields, fields_containing_dates, ["from", ])
transfer_list(fields, fields_containing_length_height_weight, ["patient's weight", "weight", "if related to a laceration. please indicate the length:", "a) height", "patient's height", "patient height", "height", ])
transfer_list(fields, fields_containing_relation, ["i signed on behalf of the claimant as", "i signed on behalf of claimant as", "if yes, what is the relation?", "i signed on behalf of the insured, as", "patient relationship to insured:", "i signed on behalf of the insured as", "if yes, what is the relationship?", "if yes, what is the relationship", "if claim is for a child, please state your relationship to the child", "relationship", "relationship to insured/policyholder (check one)", ])
transfer_list(fields, fields_containing_burn_deg, ["if related to a burn. please indicate the degree:", ])
transfer_list(fields, fields_containing_when, ["a) when do you expect improvement in the patient's capabilities?", "if you have not returned to work, when do you expect to return?", "when do you expect the patient to return to work?", "if yes, when?", ])
transfer_list(fields, fields_containing_numbers, ["policy number", "policy number:", "policy #", "customer number", "account number:", "id number:", "accident policy number", "personal account number"])
transfer_list(fields, fields_containing_diag, ["secondary diagnosis", "what diagnostic or clinical findings support your diagnosis?", "a) what is the primary diagnosis preventing your patient from working?", "diagnosis:", "secondary diagnosis:", "diagnosis remarks", "diagnosis and treatment", "diagnosis", "what diagnostic or clinical findings support your patient's work restrictions and limitations?", "primary diagnosis", "diagnostic procedure codes/description", ])

transfer_list(fields_containing_name_word, fields_containing_names, ["name of employee/policyholder", "(name)", "patient name", "full name of primary doctor", "name of doctor", "name of patient", "first name", "print or type name", "treating physician name", "provider name", "if yes, employer name", "(print name)", "Printed name", "name of patient (if not self)", "full name of treating doctor", "employer name", "full name of referring doctor/hospital", "claimant name", "name", "policyholder/employer's name", "employee name", "last name", "primary care physician name"])
fields = set.union(fields, fields_containing_name_word)

transfer_list(fields, fields_containing_addresses, ["home address (street/po box)", "street address", "hospital address", "address details:", "address", "home address", "address:", "name/address of facility", ])

transfer_list(fields, fields_containing_hospitals, ["information about your doctor(s) and/or hospital (please print)", "hospital", "hospital name", ])
transfer_list(fields, fields_descriptive,
              ["b. complete this section for disability claims only.", "if yes, please provide the following", "a routing number beginning with the number 5 is not valid", "part i: to be completed by patient", "a. information about you", "c. information about your medical providers", "this claim is for", "b. information about your disability",
               "insured/patient statement (please print)", "insured/patient statement (continued)", "employee statement (continued)", "please provide copies of all test results, operative reports, pathology reports, and/or your detailed medical statement related to the service provided to the patient.", "employee statement (please print)", "attending physician or provider of service statement (continued)", "attending physician statement", "if your hospital bill does not contain this information, please ask your doctor to complete the attending physician statement (pages 8-10 of this form.)", "attending physician or provider of service statement (please print)", "a. attending physician's statement (please print)", "attending physician statement (continued)", "attending physician statement (please print)",
               "a. complete this section for accident claims only.", "if yes, please explain", "section 4: employee (applicant) statements", "a. complete this section for pregnancy, then go to section c", "d. complete this section for hospital confinement/intensive care claims.", "section 1: employee (applicant) information - always complete",
               "c. information about the patient (if different from insured/policyholder) check one",
               "what is your treatment plan? please include all medications",
               "if yes, please provide restrictions and limitations:", "please provide the duration of these restrictions and limitations.", "current restrictions (activities patient should not do)", "if yes, please list the permanent restrictions and limitations.", "if no, please indicate the restrictions and limitations that prevent the patient from returning to work in the space provided below.", "current restrictions (activities patient should not do) and current limitations (activities patient cannot do). please be specific and understand tht a reply of \"no work\" or \"totally incapacitated\" will not enable us to evaluate the claim for benefits", "if your patient has current restrictions (activities patient should not do) and/or limitations (activities patient cannot do) list below.", "c) limitations (activities patient cannot do)", "current limitations (activities patient cannot do)",
               "cpt code",
               "v",
               "procedure/procedure code", "procedure", "if yes, what procedure was performed?", "surgical procedure",
               "c) describe reported symptoms", "what symptoms is your patient reporting about his/her condition?", "b) describe reported symptoms",
               "if yes what is the recommended frequency of treatment?", "treatment",
               "electronically signed indicator",
               "bank transit/routing number", "banking details:", "bank/financial institution information", "bank name:", "banking details",
               "name, specialty, address, phone #, fax #, treatment from, to", "(name/relationship)", "address (street, apt. #, city, state, zip)",
               "life insurance",
               "c. information about the patient", "please explain how your accident happened. (if you need more space, please attach a separate sheet of paper).", "section b. accidental injury", "c. complete this section for emergency room and/or hospital/icu confinement claims (please refer to place of service codes above)", "section 2: spouse information - complete only if applying for spouse coverage", "if yes, please explain how the work related injury/illness occured", "part ii: to be completed by attending physician or treating provider", "c. complete this section for hospital confinement/intensive care benefit claims.", "f. information about physicians and hospitals",

               "specialty", "place of service codes",
               "av order / other",
               "time of accident", "degree/specialty", "[optional employee selected benefit]", "employer selected benefit[s]", "cancel my direct deposit agreement", "employee id/payroll #",
               "contact details", "ain mgmt w/", "name, specialty, address, phone #", "through", "medical specialty", "st/po box", "other details:", "c) describe physical findings (mris, x-rays, emg/ncv studies, lab test, clinical findings, gaf etc.)", "other conditions (please attach additional information as necessary)", "return to work assessment", "d) patient's ability to perform (please check)",
               "if related to an injury, when, where and how did the injury occur?", "d. complete this section for inpatient/outpatient surgery claims (please refer to place of service codes above)", "what is your treatment plan? please include all medications.", "to be completed by physician or treating provider", "if this claim is related to normal pregnancy, please provide the following:", "section c. hospital confinement, intensive care benefit", "b. complete this section for all conditions except pregnancy, then go to sextion c", "a) describe the patient's current treatment program (include facilities name/address if applicable)", "change direct deposit account", "normal pregnancy", "restrictions and/or limitations", "sos services:", "2. for other than pregnancy, is your disability caused by",
               "d) describe physical findings (mris, x-rays, emg/ncv studies, lab test, clinical findings, gaf etc.)", "tell us how your accident happened: (if you need more space, you may attach oa separate place pf paper.)", "to be completed by attending physician or treating provider", "section 3: coverage information",
               "individual disability", "a. complete this section for normal pregnancy, then go to section c", "what is your treatment plan?", "physical capabilities", "ient referral", "b. complete this section for all conditions except pregnancy, then go to section c",
               "c) patients ability to lift/carry (please check)", "risk", "if no, when do you expect improvement in the patient's functional capacity?",
               "if this claim is related to normal pregnancy, please provide the following", "d. information about your condition", "e. complete this section for accidental injury claims", "contingent beneficiary", "if your patient has current restrictions (activities patient should not do) and/or limitation (activities patient cannot do) list below. please be specific and understand that a reply of \"no work\" or \"totally disabled\" will not enable us to evaluate your patient's claim for benefits and may result in us having to contact you for clarification.",

               "(activities patient cannot do), please initial here", "iv", "b. information about how to set-up or change your direct deposit",
               "if your patient has current restrictions (activities patient should not do) and/or limitations (activities patient cannot do) list below",
               "b) restrictions (activities patient should not do)", "other providers: please supply complete name, contact information and specialty of any other treating physicians or hospital.", "if yes, please indicate any ongoing restrictions and limitations in the space provided below.", "unknown", "ii", "policy endorsements:", "if known, please check all types of coverage you have with unum.", "b. information about the insured", "choose type of account - note: we are only able to deposit benefit payments into one account.", "primary beneficiary", "b) patient's ability to: (please check)", "facility name", "short term disability", "long term disability",
               "agent/insp:", "c. functional capacity", "the above statements are true and complete to the best of my knowledge and belief.", "please verify the transit routing number with your bank.", "e. information about physician", "full time", "section a. general information", "delivery type:",
               "dsm-iv i",
               "voluntary benefits cancer/critical illness insurance", "c) delivery type", "b. complete this section for all conditions except normal pregnancy", "degree", "if related to a fracture or dislocation, please indicate:", "branch:", "b. complete this section for diagnostic testing claims", "a. complete this section for all medical conditions", "part i: to be completed by insured/patient",
               "accident details", "what are the other conditions that prevent the patient from working?", "voluntary benefits disability", "voluntary benefits medsupport insurance", "please attach an itemized copy of your hospital bill that includes the following information. diagnosis, admission and discharge dates, name of facility and address.", "dates of inpatient hospital confinement", "iii", "if yes, please describe", "please complete this section if you are canceling your direct deposit agreement", "cpt code:", "what is the primary diagnosis preventing the patient from working?", "employee/policyholder information", "part ii: to be completed by physician or treating provider", "claim event identifier",
               "(if the patient received multiple tests, please provide dates and locations in an attached doument)", "(name / relationship)", "occupation", "c. direct deposit cancellation request", "patient information", "all other conditions", "other providers: are you aware or have you referred your patient to other treating providers? if yes, please provide complete name, contact information and specialty of any other treating physicians",
               "supplies/casting order", "group accident", "b) medications (please list all medications including dosage and frequency)", "other providers: are you aware of or have you referred your patient to other treating providers? if yes, please provide complete name, contact information and specialty of any other treating physicians.",
               "c. fuctional capacity", "set-up direct deposit", "mri", "certification",
               "next oppointment", "what type of delivery?", "what is the name of your medical condition?", "part time", "medications (please attach medication log)", "b. information about the insured/policyholder", "are there other conditions that prevent your patient from working? if so, please list with information as follows:", ])
# print("\n".join(fields_containing_name_word))


print(len(fields))
print("\",\n\"".join(fields_containing_diag))

total = [fields_containing_dates,
         fields_containing_compound_names,
         fields_containing_names,
         fields_containing_SSN,
         fields_containing_gender,
         fields_containing_mail,
         fields_containing_fax,
         fields_containing_tele,
         fields_containing_addresses,
         fields_containing_icd,
         fields_containing_MI,
         fields_containing_zip,
         fields_containing_yes_no,
         fields_containing_signature,
         fields_containing_mailing_address,
         fields_containing_state,
         fields_containing_city,
         fields_containing_tax_id,
         fields_containing_hospitals,
         fields_containing_num_hours,
         fields_containing_length_height_weight,
         fields_containing_relation,
         fields_containing_burn_deg,
         fields_containing_when,
         fields_containing_numbers,
         fields_containing_diag]

print(sum(list(map(lambda item: len(item), total))))

# print(len(fields))
# import Levenshtein # https://rawgit.com/ztane/python-Levenshtein/master/docs/Levenshtein.html

import pickle

with open("./buckets_of_fields.pkl", 'wb') as f:
    pickle.dump(total, f)  # dumps get the string
    # cities,addresses,hospitals,codes,description
